# Travis configuration for Learning C
# Author: Javier Balloffet <javier.balloffet@gmail.com>

os: linux
dist: bionic
language: c
compiler: gcc

stages:
  - build

addons:
  apt:
    packages:
      - libopencv-dev
      - libgtk-3-dev
      - libvlc-dev

jobs:
  include:
    # Build application
    - name: "build-app"
      stage: build
      script:
        - bash ci/build_app.sh
